### ISSUE TITLE
Refine upstream/downstream descriptions

### ISSUE THREAD

**Issue by ichdasich** [ichdasich/draft-routing-operations-terminology#3]
Feedback from nanog: Reading through that, there are some definitions I think could be done better.

In section 4.2 you have:
 Downstream:
   In a direct relationship between two ASes the one receiving upstream from the other. (See: [RFC9234], also known as the customer in a customer-provider relationship.)
 Upstream:
   In a direct relationship between two ASes the one providing upstream to the other. (See: [RFC9234], also known as the provider in a customer-provider relationship.)
 Providing Transit:
   Forwarding packets destined for addresses in an advertised prefix, while advertising a full BGP table or default route to the neighbor.
 Providing Upstream:
   See: Providing Transit

Especially with the definition for "Upstream", it took me reading the whole of the section to understand that you don't actually have a circular definition there. If you change the definitions in the "Downstream" and "Upstream" sections to refer to providing or receiving "transit" instead of "upstream" I feel that it would read more clearly as well as pointing to a term has its own definition without pointing to another term.

**Comment by wtremmel** [comment]
Suggestion: 
- change the term to "Upstream Provider" / "Transit Provider" (synonym)
-  Put the definition into Upstream Provider
- define Downstream Customer only as "a provider getting Internet connectivity from a Transit Provider" (needs to be phrased more carefully)

**Comment by wtremmel** [comment]
Possible definition, btw - I like yours as well....

### Upstream Provider / Transit Provider
An Internet Service Provider either announcing the full BGP routing table to its customers (also called "Downstream Customers") _or_ allowing these customers to point a default route towards it. 

### Downstream Customer
An Internet Service Provider either receiving a full BGP table from an Upstream Provider _or_ pointing a default route to this Upstream Provider.

**Comment by wtremmel** [comment]
See branch updownstream for a suggestion
